### ISSUE TITLE
how to sync or backup Nano Defender for Firefox and Nano Adblocker Core for Firefox?

### ISSUE THREAD

**Issue by candrapersada** [LiCybora/NanoCoreFirefox#14]
how to sync or backup addons Nano Defender for Firefox and addons Nano Adblocker Core for Firefox?

**Comment by LiCybora** [comment]
Due to unavailability from AMO, Firefox Sync will not sync the addon itself. However, If you manually install two Nano Adblocker on two Firefox separately and both login to the same Firefox Sync account, you may still able to export/import your filters and/or settings to/from cloud storage.

For local backup, just open the dashboard > Settings > Back up to file (at bottom). For restore, click "Restore from file..." next to "Back up to file" button. You may also export to file for custom filters/rules/whitelist.

At this moment Nano Defender is not customizable I guess you don't need a backup, just reinstall is fine.

**Comment by candrapersada** [comment]
but why install Nano Defender for Firefox and Nano Adblocker Core for Firefox, use a separate repo, not one

**Comment by LiCybora** [comment]
Because this (Nano Adblocker) repo is not an official port, while Nano Defender is official port.

Also these two are separate extensions. It is normal to separate different codes in different repo.
